spring:
  application:
    name: uaa
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    liquibase-schema: public
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
