application:
  name: orbit-captcha
  server:
    port: 7006
eureka: http://orbit-discovery:7000/eureka,http://127.0.0.1:7000/eureka
redis:
  addr: redis-server:6379
captcha:
  height: 60
  width: 200
  mode: 2
  complex-of-noise-text: 0
  complex-of-noise-dot:  0
  use-simple-font: false
  show-hollow-line: false
  show-noise-dot: false
  show-noise-text: true
  show-slime-line: false
  show-sine-line: false
  len: 8