spring:
  application:
    name: registry
  security:
    user:
      name: admin
      password: public
server:
  port: 7000
  ssl:
    #keytool -genkeypair -alias orbit.com -storetype PKCS12 -keyalg RSA -validity 365 -keystore .keystore
    key-store: ${user.home}/.keystore
    key-store-password: 59a84cbf83227a35
    key-store-type: PKCS12
    key-alias: orbit.com
    protocol: TLSv1.2

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/