spring:
  profiles:
    active: dev
  application:
    name: registry
  security:
    user:
      name: admin
      password: public
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inmaytide/configurations-repositories.git
          search-paths: configurations
        prefix: /configurations
server:
  port: 7000
  ssl:
    key-store: ${user.home}/.certificates/server.jks
    key-store-password: 59a84cbf83227a35
    key-store-type: PKCS12
    key-alias: 1
    protocol: TLSv1.2

eureka:
  dashboard:
    path: /dashboard
  instance:
    hostname: api.orbit.com
    status-page-url: https://${eureka.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.hostname}:${server.port}/actuator/health
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://admin:public@${eureka.instance.hostname}:${server.port}/eureka/