spring:
  application:
    name: configurations
  # profiles:
    # active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inmaytide/configurations-repositories.git
          search-paths: configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery.orbit.com:7000/eureka/
server:
  port: 7001