server:
  port: 7001
  ssl:
    key-store: ${user.home}/.keystore
    key-store-password: 59a84cbf83227a35
    key-store-type: PKCS12
    key-alias: orbit.com
    protocol: TLSv1.2
spring:
  application:
    name: configurations
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inmaytide/configurations-repositories.git
          search-paths: configurations
eureka:
  instance:
    status-page-url: https://${eureka.hostname}:${server.port}/actuator/info
    health-check-url: https://${eureka.hostname}:${server.port}/actuator/health
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: gateway.orbit.com
  client:
    serviceUrl:
      defaultZone: https://admin:public@registry.orbit.com:7000/eureka/